export const light = {
    heading: "#52665A",
    background: "#FFFFFF",
    body_dark: "#738078",
    green_dark: "#2B7A4B",
    green: "#32B768",
    green_light: "#DAF2E4",
    body_light: "#AAB2AD",
    shape: "#F0F0F0",
    white: "#FFFFFF",
    gray: "#CFCFCF",
    blue: "#3D7199",
    blue_light: "#EBF6FF",
    red: "#E83F5B",
};
